config/routes.rb
Rails.application.routes.draw do
  resources :rss_feeds do
  	collection do 
  		get :refresh
  	end
  	resources :rss_entries
  end
  resources :rss_entries
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rss_entry.rb
class RssEntry < ApplicationRecord
  belongs_to :rss_feed
  paginates_per 5
  default_scope { order(date: :desc) }
end

app/models/rss_feed.rb
class RssFeed < ApplicationRecord
	has_many :rss_entries, dependent: :destroy

	default_scope { order(created_at: :desc) }

	after_create do |feed|
		RssFeedsHelper.update_feed feed
	end

	def title
		begin
			return URI.parse(url).host if super.empty?
		rescue
		end
		super
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	skip_before_action :verify_authenticity_token
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@rss_feeds = RssFeed.all
  	# RssFeedsHelper.update_feeds
  end
end

app/controllers/rss_entries_controller.rb
class RssEntriesController < ApplicationController
  before_action :set_rss_entry, only: [:show, :edit, :update, :destroy]

  # GET /rss_entries
  # GET /rss_entries.json
  def index
    if params[:rss_feed_id]
      collection = RssFeed.find(params[:rss_feed_id]).rss_entries
    else
      collection = RssEntry.all
    end
    @rss_entries = collection.page(params[:page].to_i)
  end

  # GET /rss_entries/1
  # GET /rss_entries/1.json
  def show
  end

  # GET /rss_entries/new
  def new
    @rss_entry = RssEntry.new
  end

  # GET /rss_entries/1/edit
  def edit
  end

  # POST /rss_entries
  # POST /rss_entries.json
  def create
    @rss_entry = RssEntry.new(rss_entry_params)

    respond_to do |format|
      if @rss_entry.save
        format.html { redirect_to @rss_entry, notice: 'Rss entry was successfully created.' }
        format.json { render :show, status: :created, location: @rss_entry }
      else
        format.html { render :new }
        format.json { render json: @rss_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rss_entries/1
  # PATCH/PUT /rss_entries/1.json
  def update
    respond_to do |format|
      if @rss_entry.update(rss_entry_params)
        format.html { redirect_to @rss_entry, notice: 'Rss entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @rss_entry }
      else
        format.html { render :edit }
        format.json { render json: @rss_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rss_entries/1
  # DELETE /rss_entries/1.json
  def destroy
    @rss_entry.destroy
    respond_to do |format|
      format.html { redirect_to rss_entries_url, notice: 'Rss entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rss_entry
      @rss_entry = RssEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rss_entry_params
      params.require(:rss_entry).permit(:is_read)
    end
end

app/controllers/rss_feeds_controller.rb
class RssFeedsController < ApplicationController
  before_action :set_rss_feed, only: [:show, :edit, :update, :destroy]

  # GET /rss_feeds
  # GET /rss_feeds.json
  def index
    @rss_feeds = RssFeed.all
    render layout: false
  end

  # GET /rss_feeds/1
  # GET /rss_feeds/1.json
  def show
    render layout: false
  end

  def refresh
    RssFeedsHelper.update_feeds
    render json: { success: true }
  end

  # GET /rss_feeds/new
  def new
    @rss_feed = RssFeed.new
  end

  # GET /rss_feeds/1/edit
  def edit
  end

  # POST /rss_feeds
  # POST /rss_feeds.json
  def create
    @rss_feed = RssFeed.new(rss_feed_params)

    respond_to do |format|
      if @rss_feed.save
        format.html { redirect_to @rss_feed, notice: 'Rss feed was successfully created.' }
        format.json { render :show, status: :created, location: @rss_feed }
      else
        format.html { render :new }
        format.json { render json: @rss_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rss_feeds/1
  # PATCH/PUT /rss_feeds/1.json
  def update
    respond_to do |format|
      if @rss_feed.update(rss_feed_params)
        format.html { redirect_to @rss_feed, notice: 'Rss feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @rss_feed }
      else
        format.html { render :edit }
        format.json { render json: @rss_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rss_feeds/1
  # DELETE /rss_feeds/1.json
  def destroy
    @rss_feed.destroy
    respond_to do |format|
      format.html { redirect_to rss_feeds_url, notice: 'Rss feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rss_feed
      @rss_feed = RssFeed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rss_feed_params
      params.require(:rss_feed).permit(:url, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rss_feeds_helper.rb
module RssFeedsHelper

	def self.update_feeds
		RssFeed.all.each do |feed|
			self.update_feed feed
		end
	end

	def self.update_feed feed
		require 'rss'
	  	require 'open-uri'
	  	begin
	  		fetched_rss_content = open(feed.url, read_timeout: 5).read
	  		fetched_rss_entries = RSS::Parser.parse(fetched_rss_content, false).items
			# feed.rss_entries.destroy
	  		ActiveRecord::Base.transaction do
				fetched_rss_entries.each do |fetched_rss_entry|
					return if feed.rss_entries.find_by_url(fetched_rss_entry.link)
					rss_entry = RssEntry.new
					rss_entry.rss_feed = feed
					rss_entry.title = fetched_rss_entry.title
					rss_entry.date = fetched_rss_entry.pubDate || fetched_rss_entry.dc_date
					rss_entry.content = fetched_rss_entry.description
					rss_entry.url = fetched_rss_entry.link
					rss_entry.save! 
				end
			end
		rescue
			# TODO: tell user if something is wrong with the URL
		end
	end


end

app/views/home/index.html.erb
<%= react_component 'Main' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ideematic &mdash; ReactJS</title>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
    <div class="text-center m-2">Rails v.<%= Rails.version %></div>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/rss_entries/_list.html.erb
<div data-id="<%= entry.id %>" class="list-group-item flex-column align-items-start rss-entry <%= 'is-read' if entry.is_read? %>">
  <div class="d-flex w-100 justify-content-between">
    <h5 class="mb-1">
    	<a href="<%= entry.url %>" target="_blank"><%= entry.title %></a>
    </h5>
    <small class="text-muted text-nowrap mt-1 pl-1"><%= entry.date.strftime("%d/%m/%Y") unless entry.date.nil? %></small>
  </div>
  <p class="mb-1"><%= truncate strip_tags(entry.content), length: 300 %></p>
  <div class="text-right">
  	<small class="text-muted">
  	  <a href="#" class="mark-as-read">Marquer comme lu</a>
  	  <span class="read">&check; Lu</span>
  	</small>
  </div>
</div>

app/views/rss_entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rss Entries</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rss_entries.each do |rss_entry| %>
      <tr>
        <td><%= link_to 'Show', rss_entry %></td>
        <td><%= link_to 'Edit', edit_rss_entry_path(rss_entry) %></td>
        <td><%= link_to 'Destroy', rss_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rss Entry', new_rss_entry_path %>

app/views/rss_feeds/_all.html.erb
<% @rss_feeds.each do |feed| %>
  <%= render partial: "rss_feeds/list", locals: { feed: feed } %>
<% end %>

app/views/rss_feeds/_list.html.erb
<div class="col-md-6 rss-feed" data-id="<%= feed.id %>">
	<div class="card mb-4 shadow-sm">
	  <div class="card-body">
	    <h4 class="card-title mb-0">
	    	<a href="#" class="delete-feed close pull-right">&times;</a>
	    	Les news de <%= feed.title %>
	    </h4>
	  </div>
	  <div class="list-group list-group-flush">
	  	<% entries = feed.rss_entries.page(params[:page].to_i) %>
	    <% entries.each do |entry| %>
	    	<%= render partial: "rss_entries/list", locals: { entry: entry } %>
	    <% end %>

	    <% if entries.length == 0 %>
	      <div class="list-group-item list-group-item-danger">
	      	Pas de news :(
	      </div>
	    <% end %>

	    <%= paginate entries, theme: 'twitter-bootstrap-4', pagination_class: 'mb-0', params: { id: feed.id, action: "show", controller: "rss_feeds"} %>

	  </div>
	</div>
</div>

app/views/rss_feeds/index.html.erb
<%= render partial: "rss_feeds/all", locals: { rss_feeds: @rss_feeds } %>

app/views/rss_feeds/show.html.erb
<%= render partial: "rss_feeds/list", locals: { feed: @rss_feed } %>